### ISSUE TITLE
Videos from youtube "- Topic" channels do not work

### ISSUE THREAD

**Issue by ducc** [ducc/JavaMusicBot#5]

**Comment by ducc** [comment]
Exclude from search results?

**Comment by SilverCory** [comment]
This is funny.

**Comment by ducc** [comment]
xd fix it then genius

**Comment by hlaaftana** [comment]
As in music? Youtube autogenerated music videos only play in the US

**Comment by ducc** [comment]
YEP and dap bot is canada :(

**Comment by ducc** [comment]
Only solution is relocating servers/a proxy which is not in the scope of this project.
