### ISSUE TITLE
I wont self host

### ISSUE THREAD

**Issue by TheFallingPie** [ducc/JavaMusicBot#78]
I wont self host I wont self host I wont self host I wont self host I wont self host I wont self host I wont self host I wont self host I wont self host I wont self host I wont self host I wont self host I wont self host I wont self host I wont self host I wont self host I wont self host I wont self host I wont self host I wont self host I wont self host I wont self host I wont self host I wont self host I wont self host

**Comment by not-john** [comment]
Understandable, have a great day.

**Comment by TheFallingPie** [comment]
Understandable, have a ducc day.

**Comment by not-john** [comment]
ok
