### ISSUE TITLE
I won't self-host.. because I can't code

### ISSUE THREAD

**Issue by not-john** [ducc/JavaMusicBot#79]
I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code I won't self-host because I can't code

**Comment by DoNotSpamPls** [comment]
ok
